---
- name: Install Apache Tomcat on Ubuntu, RedHat, AWS Linux
  hosts: g1 g2
  become: true
  tasks:
    - name: Get user information
      setup:
      register: ansible_info

    - name: Get user variables
      set_fact:
        username: "{{ ansible_info.ansible_facts.ansible_user_id }}"

    - name: Update package manager cache
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
          when: ansible_pkg_mgr == "apt"
        - name: Update yum cache
          yum:
            update_cache: yes
          when: ansible_pkg_mgr == "yum"
          
    - name: Ensure Git is installed
      become: true
      package:
        name: git
        state: present
        
    - name: Install Java (OpenJDK)
      block:
        - name: Install openjdk-11-jdk using apt
          apt:
            name: openjdk-11-jdk
            state: present
          when: ansible_pkg_mgr == "apt"
        - name: Install openjdk-11-jdk using yum
          yum:
            name: java-11-openjdk
            state: present
          when: ansible_pkg_mgr == "yum"

    - name: Add User to ROOT GROUP
      user:
        name: "{{ username }}"
        groups: root
        append: yes
      become: yes
    - name: Download and extract Apache Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.15/bin/apache-tomcat-10.1.15.tar.gz
        dest: /opt
    - name: Extract Tomcat archive
      unarchive:
        src: /opt/apache-tomcat-10.1.15.tar.gz
        dest: /opt
        remote_src: yes
    - name: Remove existing toncat dir
      command: rm -rf /opt/tomcat
    - name: Rename Tomcat directory
      command: mv -f /opt/apache-tomcat-10.1.15 /opt/tomcat

    - name: Set permissions on /opt/
      ansible.builtin.file:
        path: /opt/
        mode: '0777'
        recurse: yes
      become: yes
    - name: Configure service for Tomcat
      command: /opt/tomcat/bin/startup.sh
      # command: /opt/tomcat/bin/shutdown.sh && /opt/tomcat/bin/startup.sh
...
